name: CI/CD
on: push
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set release version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        if: startsWith(github.ref, 'refs/tags/')
      - name: Build wheel
        run: python3 setup.py bdist_wheel
      - name: Upload wheel
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/*.whl

  release:
    name: Release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    steps:
      - name: Download wheel
        uses: actions/download-artifact@v2
        with:
          name: dist
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.whl